# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bipador.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(724, 575)
        MainWindow.setAcceptDrops(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("app.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAnimated(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tbPedido = QtWidgets.QLineEdit(self.centralwidget)
        self.tbPedido.setEnabled(True)
        self.tbPedido.setStatusTip("")
        self.tbPedido.setText("")
        self.tbPedido.setObjectName("tbPedido")
        self.horizontalLayout_4.addWidget(self.tbPedido)
        self.btConfirmar = QtWidgets.QPushButton(self.centralwidget)
        self.btConfirmar.setEnabled(True)
        self.btConfirmar.setCheckable(False)
        self.btConfirmar.setObjectName("btConfirmar")
        self.horizontalLayout_4.addWidget(self.btConfirmar)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(20)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lbTotalCaixa = QtWidgets.QLabel(self.centralwidget)
        self.lbTotalCaixa.setEnabled(True)
        self.lbTotalCaixa.setObjectName("lbTotalCaixa")
        self.horizontalLayout_2.addWidget(self.lbTotalCaixa)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.lbTotalAparelho = QtWidgets.QLabel(self.centralwidget)
        self.lbTotalAparelho.setObjectName("lbTotalAparelho")
        self.horizontalLayout.addWidget(self.lbTotalAparelho)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(1)
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lbTotal = QtWidgets.QLabel(self.centralwidget)
        self.lbTotal.setObjectName("lbTotal")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lbTotal)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.tbAbas = QtWidgets.QTabWidget(self.centralwidget)
        self.tbAbas.setEnabled(False)
        self.tbAbas.setObjectName("tbAbas")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.lvIMEI = QtWidgets.QListWidget(self.tab)
        self.lvIMEI.setEnabled(False)
        self.lvIMEI.setObjectName("lvIMEI")
        self.verticalLayout_2.addWidget(self.lvIMEI)
        self.tbAbas.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tbDescricao = QtWidgets.QTableWidget(self.tab_2)
        self.tbDescricao.setEnabled(False)
        self.tbDescricao.setObjectName("tbDescricao")
        self.tbDescricao.setColumnCount(0)
        self.tbDescricao.setRowCount(0)
        self.tbDescricao.horizontalHeader().setVisible(False)
        self.tbDescricao.horizontalHeader().setHighlightSections(False)
        self.tbDescricao.verticalHeader().setVisible(False)
        self.tbDescricao.verticalHeader().setHighlightSections(False)
        self.verticalLayout_3.addWidget(self.tbDescricao)
        self.tbAbas.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tbAbas)
        self.pbProgresso = QtWidgets.QProgressBar(self.centralwidget)
        self.pbProgresso.setEnabled(True)
        self.pbProgresso.setMaximum(100)
        self.pbProgresso.setProperty("value", 0)
        self.pbProgresso.setObjectName("pbProgresso")
        self.verticalLayout.addWidget(self.pbProgresso)
        self.tbIMEI = QtWidgets.QLineEdit(self.centralwidget)
        self.tbIMEI.setEnabled(False)
        self.tbIMEI.setObjectName("tbIMEI")
        self.verticalLayout.addWidget(self.tbIMEI)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btEnviar = QtWidgets.QPushButton(self.centralwidget)
        self.btEnviar.setEnabled(False)
        self.btEnviar.setMouseTracking(False)
        self.btEnviar.setTabletTracking(False)
        self.btEnviar.setAcceptDrops(False)
        self.btEnviar.setObjectName("btEnviar")
        self.horizontalLayout_5.addWidget(self.btEnviar)
        self.btCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.btCancelar.setEnabled(False)
        self.btCancelar.setObjectName("btCancelar")
        self.horizontalLayout_5.addWidget(self.btCancelar)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tbAbas.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tbPedido, self.btConfirmar)
        MainWindow.setTabOrder(self.btConfirmar, self.tbIMEI)
        MainWindow.setTabOrder(self.tbIMEI, self.btEnviar)
        MainWindow.setTabOrder(self.btEnviar, self.btCancelar)
        MainWindow.setTabOrder(self.btCancelar, self.tbAbas)
        MainWindow.setTabOrder(self.tbAbas, self.lvIMEI)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bipador"))
        self.tbPedido.setPlaceholderText(_translate("MainWindow", "Nº Nota"))
        self.btConfirmar.setText(_translate("MainWindow", "Confirmar"))
        self.label.setText(_translate("MainWindow", "Total de Caixas:"))
        self.lbTotalCaixa.setText(_translate("MainWindow", "0"))
        self.label_3.setText(_translate("MainWindow", "Total de Aparelhos:"))
        self.lbTotalAparelho.setText(_translate("MainWindow", "0"))
        self.label_5.setText(_translate("MainWindow", "Total: "))
        self.lbTotal.setText(_translate("MainWindow", "0"))
        self.tbAbas.setTabText(self.tbAbas.indexOf(self.tab), _translate("MainWindow", "Bipagem"))
        self.tbAbas.setTabText(self.tbAbas.indexOf(self.tab_2), _translate("MainWindow", "Descrição do Pedido"))
        self.tbIMEI.setPlaceholderText(_translate("MainWindow", "IMEI / CX Master"))
        self.btEnviar.setText(_translate("MainWindow", "Enviar"))
        self.btCancelar.setText(_translate("MainWindow", "Cancelar"))
